#!/usr/bin/env bash
LC_ALL=C

master_branch="master"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

#####################################################################
# Branch-Namen müssen einem gewissen regulären Ausdruck entsprechen #
#####################################################################

# execute phpunit
#./vendor/bin/phpunit tests
#x=$?

#if [ $x != 0 ]; then
#    echo "phpstan error, exit code = $x"
#    exit $x
#fi

# execute phpstan
./vendor/bin/phpstan --generate-baseline
x=$?

exit $x
